require "user.keymaps"
require "user.plugins"
require "user.autopairs"
require "user.options"
require "user.lsp-setup"
require "user.cmp"
require "user.nvim-tree"
require "user.treesitter"
require "user.telescope"
require "user.colorizer"
require "user.illuminate"
require "user.web-dev-icons"
require "user.lualine"
require "user.todo-comments"
require "user.symbols-outline"
-- require "user.rooter"
