# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "everforest"

command_timeout = 700

# Inserts a blank line between shell prompts
format = " $all"
add_newline = true

# git
[git_branch]
style = "bold overlay2"

# Go
[golang]
symbol = " "
format = "[$symbol](fg:sky)[$version](bold sky) "

# Python
[python]
symbol = " "
format = "[$symbol](fg:green)[($version )]($style)[($virtualenv )](bold yellow)"
style = "bold green"

# Lua
[lua]
symbol = " "
style = "bold blue"
format = "[$symbol($version )]($style)"

# Elixir
[elixir]
symbol = " "
format = "[$symbol($version \\(OTP $otp_version\\) )]($style)"

[package]
disabled = true

# [docker_context]
# disabled = true


# Catppuccin mocha theme
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"

[palettes.everforest]
bg_dim = "#232a2e"
bg0 = "#2d353b"
bg1 = "#343f44"
bg2 = "#3d484d"
bg3 = "#475258"
bg4 = "#4f585e"
bg5 = "#56635f"
bg_visual = "#543a48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3a515d"
bg_yellow = "#4d4c43"
fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"
